image: "alpine"
before_script:
  - apk update && apk add cargo cmake make libx11-dev xorg-dev libglu1-mesa-dev && apk upgrade

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script: "cargo build"

job2:
  stage: test
  script: "cargo test gitlab --lib"

after_script:
  - cargo clean
