image: "alpine"
before_script:
  - apk update && apk add cargo && apk upgrade

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script: "cargo build"

job2:
  stage: test
  script: "cargo test"

after_script:
  - cargo clean
