[package]
name = "rust_gl"
version = "0.1.0"
authors = ["alex <alexandre.fourcat@epitech.eu>"]

[dependencies]
gl = "0.10.0"
nalgebra = "0.15.0"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"