[package]
name = "gust"
version = "0.1.0"
authors = ["alex <alexandre.fourcat@epitech.eu>"]
autoexamples = true

[dependencies]
gl = "*"
nalgebra = "*"
image = "*"
lazy_static = "*"
freetype-rs = "*"
rayon = "*"
crossbeam = "*"
alga = "*"
glfw = "*"
